=== krokettenkoal/khkh_xldM/MdlxA2B/BindPreset.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="BindPreset" targetNamespace="http://tempuri.org/BindPreset.xsd" elementFormDefault="qualified" xmlns="http://tempuri.org/BindPreset.xsd" xmlns:mstns="http://tempuri.org/BindPreset.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="preset">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="item" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:complexContent>
              <xs:restriction base="xs:anyType">
                <xs:sequence>
                  <xs:element name="display-name" type="xs:string" maxOccurs="1" minOccurs="1" />
                  <xs:element name="body-mdlx" type="xs:string" minOccurs="0" maxOccurs="1" />
                  <xs:element name="body-mset" type="xs:string" maxOccurs="1" minOccurs="0" />
                  <xs:element name="right-hand-mdlx" type="xs:string" maxOccurs="1" minOccurs="0" />
                  <xs:element name="right-hand-mset" type="xs:string" maxOccurs="1" minOccurs="0" />
                  <xs:element name="right-hand-joint" type="xs:int" maxOccurs="1" minOccurs="0" />
                  <xs:element name="left-hand-mdlx" type="xs:string" maxOccurs="1" minOccurs="0" />
                  <xs:element name="left-hand-mset" type="xs:string" maxOccurs="1" minOccurs="0" />
                  <xs:element name="left-hand-joint" type="xs:int" maxOccurs="1" minOccurs="0" />
                </xs:sequence>
              </xs:restriction>
            </xs:complexContent>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== krokettenkoal/khkh_xldM/khkh_xldMii/BindPreset.xml
<?xml version="1.0" encoding="windows-1250" ?>
<preset
  xmlns="http://tempuri.org/BindPreset.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://tempuri.org/BindPreset.xsd BindPreset.xsd"
  >
  <item>
    <display-name>Sola</display-name>
    <body-mdlx>P_EX100.mdlx</body-mdlx>
    <body-mset>P_EX100.mset</body-mset>
  </item>
  <item>
    <display-name>Sola with kb</display-name>
    <body-mdlx>P_EX100.mdlx</body-mdlx>
    <body-mset>P_EX100.mset</body-mset>
    <right-hand-mdlx>W_EX010.mdlx</right-hand-mdlx>
    <right-hand-mset>W_EX010.mset</right-hand-mset>
    <right-hand-joint>178</right-hand-joint>
  </item>
  <item>
    <display-name>Sola valor-form with kb</display-name>
    <body-mdlx>P_EX100_BTLF.mdlx</body-mdlx>
    <body-mset>P_EX100_BTLF.mset</body-mset>
    <right-hand-mdlx>W_EX010_U0.mdlx</right-hand-mdlx>
    <right-hand-mset>W_EX010_BTLF_R.mset</right-hand-mset>
    <right-hand-joint>178</right-hand-joint>
    <left-hand-mdlx>W_EX010_W0.mdlx</left-hand-mdlx>
    <left-hand-mset>W_EX010_BTLF_L.mset</left-hand-mset>
    <left-hand-joint>86</left-hand-joint>
  </item>
  <item>
    <display-name>Sola wizdom-form with kb</display-name>
    <body-mdlx>P_EX100_MAGF.mdlx</body-mdlx>
    <body-mset>P_EX100_MAGF.mset</body-mset>
    <right-hand-mdlx>W_EX010.mdlx</right-hand-mdlx>
    <right-hand-mset>W_EX010_MAGF.mset</right-hand-mset>
    <right-hand-joint>178</right-hand-joint>
  </item>
  <item>
    <display-name>Sola trinity-form with kb</display-name>
    <body-mdlx>P_EX100_TRIF.mdlx</body-mdlx>
    <body-mset>P_EX100_TRIF.mset</body-mset>
    <right-hand-mdlx>W_EX010_U0.mdlx</right-hand-mdlx>
    <right-hand-mset>W_EX010_TRIF_R.mset</right-hand-mset>
    <right-hand-joint>178</right-hand-joint>
    <left-hand-mdlx>W_EX010_W0.mdlx</left-hand-mdlx>
    <left-hand-mset>W_EX010_TRIF_L.mset</left-hand-mset>
    <left-hand-joint>86</left-hand-joint>
  </item>
  <item>
    <display-name>Sola ultimate-form with kb</display-name>
    <body-mdlx>P_EX100_ULTF.mdlx</body-mdlx>
    <body-mset>P_EX100_ULTF.mset</body-mset>
    <right-hand-mdlx>W_EX010_U0.mdlx</right-hand-mdlx>
    <right-hand-mset>W_EX010_ULTF_R.mset</right-hand-mset>
    <right-hand-joint>178</right-hand-joint>
    <left-hand-mdlx>W_EX010_W0.mdlx</left-hand-mdlx>
    <left-hand-mset>W_EX010_ULTF_L.mset</left-hand-mset>
    <left-hand-joint>86</left-hand-joint>
  </item>
  <item>
    <display-name>Sola kh1drive with kb</display-name>
    <body-mdlx>P_EX100_KH1F.mdlx</body-mdlx>
    <body-mset>P_EX100_KH1F.mset</body-mset>
    <right-hand-mdlx>W_EX010_U0.mdlx</right-hand-mdlx>
    <right-hand-mset>W_EX010.mset</right-hand-mset>
    <right-hand-joint>178</right-hand-joint>
  </item>
  <item>
    <display-name>Sola knightmare ver with kb</display-name>
    <body-mdlx>P_EX100_NM.mdlx</body-mdlx>
    <body-mset>P_EX100.mset</body-mset>
    <right-hand-mdlx>W_EX010_E0.mdlx</right-hand-mdlx>
    <right-hand-mset>W_EX010.mset</right-hand-mset>
    <right-hand-joint>178</right-hand-joint>
  </item>
  <item>
    <display-name>Sola tron ver with kb</display-name>
    <body-mdlx>P_EX100_TR.mdlx</body-mdlx>
    <body-mset>P_EX100.mset</body-mset>
    <right-hand-mdlx>W_EX010_90.mdlx</right-hand-mdlx>
    <right-hand-mset>W_EX010.mset</right-hand-mset>
    <right-hand-joint>178</right-hand-joint>
  </item>
  <item>
    <display-name>Sola willie ver with kb</display-name>
    <body-mdlx>P_EX100_WI.mdlx</body-mdlx>
    <body-mset>P_EX100.mset</body-mset>
    <right-hand-mdlx>W_EX010_60.mdlx</right-hand-mdlx>
    <right-hand-mset>W_EX010.mset</right-hand-mset>
    <right-hand-joint>178</right-hand-joint>
  </item>
  <item>
    <display-name>DUMMY</display-name>
    <body-mdlx>A.mdlx</body-mdlx>
    <body-mset>A.mset</body-mset>
  </item>
  <item>
    <display-name>---</display-name>
  </item>
  <item>
    <display-name>Roxas with kb</display-name>
    <body-mdlx>P_EX110.mdlx</body-mdlx>
    <body-mset>P_EX110.mset</body-mset>
    <right-hand-mdlx>W_EX010_U0.mdlx</right-hand-mdlx>
    <right-hand-mset>W_EX010_RX.mset</right-hand-mset>
    <right-hand-joint>172</right-hand-joint>
  </item>
  <item>
    <display-name>Roxas with 2 keyblades</display-name>
    <body-mdlx>P_EX110_BTLF.mdlx</body-mdlx>
    <body-mset>P_EX110_BTLF.mset</body-mset>
    <right-hand-mdlx>W_EX010_U0.mdlx</right-hand-mdlx>
    <right-hand-mset>W_EX010_RX_BTLF_R.mset</right-hand-mset>
    <right-hand-joint>172</right-hand-joint>
    <left-hand-mdlx>W_EX010_W0.mdlx</left-hand-mdlx>
    <left-hand-mset>W_EX010_RX_BTLF_L.mset</left-hand-mset>
    <left-hand-joint>63</left-hand-joint>
  </item>
  <item>
    <display-name>---</display-name>
  </item>
  <item>
    <display-name>Cephiroth</display-name>
    <body-mdlx>N_HB590_BTL.mdlx</body-mdlx>
    <body-mset>N_HB590_BTL.mset</body-mset>
  </item>
  <item>
    <display-name>Dusk</display-name>
    <body-mdlx>M_EX990.mdlx</body-mdlx>
    <body-mset>M_EX990.mset</body-mset>
  </item>
  <item>
    <display-name>Kairi is Hi poly</display-name>
    <body-mdlx>H_EX700.mdlx</body-mdlx>
    <body-mset>EEH10702E.mset</body-mset>
  </item>
  <item>
    <display-name>---</display-name>
  </item>
  <!-- mdlx names: http://kh-vids.net/threads/im-in-need-of-kh2-weapon-models-movesets.91722/ -->
  <item>
    <display-name>M_EX420 Schattenschalk (opponent! /Enemy!)</display-name>
    <body-mdlx>M_EX420.mdlx</body-mdlx>
    <body-mset>M_EX420.mset</body-mset>
  </item>
  <item>
    <display-name>B_NM100 Prison Keeper (Boss!)</display-name>
    <body-mdlx>B_NM100.mdlx</body-mdlx>
    <body-mset>B_NM100.mset</body-mset>
  </item>
  <item>
    <display-name>B_EX180</display-name>
    <body-mdlx>B_EX180.mdlx</body-mdlx>
    <body-mset>B_EX180.mset</body-mset>
  </item>
  <item>
    <display-name>P_AL000</display-name>
    <body-mdlx>P_AL000.mdlx</body-mdlx>
    <body-mset>P_AL000.mset</body-mset>
  </item>
</preset>
